application: multi-user-blog
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/stylesheets
  static_dir: static/stylesheets

- url: /.*
  script: app.views.main.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
