runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

- url: /style
  static_dir: style

- url: /js
  static_dir: js

libraries:
- name: jinja2
  version: latest
